#! /bin/sh -

REQ_UP_STOP="UPDATE TTPHP_REQUETE SET STATUT = CASE WHEN STATUT = 'En cours' THEN 'A stopper' END WHERE PID IS NOT NULL OR STATUT = 'En cours'"

sqlplus -s ${REPIMMO_USER}/${REPIMMO_PASS}@${REPIMMO_SID} <<EOF
${REQ_UP_STOP};
COMMIT;
EXIT
EOF
